"""Public Knowledge Asset core domain."""

from .domain import (
    AssetRelationship,
    ContentReference,
    KnowledgeAsset,
    KnowledgeAssetId,
    KnowledgeAssetKind,
    KnowledgeAssetStatus,
    Owner,
    RelationshipType,
    SemanticVersion,
    SeriesPolicy,
    SuccessorSummary,
)
from .errors import (
    DuplicateOwner,
    DuplicateRelationship,
    ImmutableAcceptedAsset,
    InvalidContentReference,
    InvalidKnowledgeAssetId,
    InvalidKnowledgeAssetKind,
    InvalidLifecycleTransition,
    InvalidOwner,
    InvalidRelationship,
    InvalidSemanticVersion,
    InvalidSuccessor,
    KindIdentifierMismatch,
    KnowledgeAssetAlreadyExists,
    KnowledgeAssetError,
    KnowledgeAssetNotFound,
    LastOwnerRemoval,
    RelationshipNotFound,
    RelationshipTargetNotFound,
    SeriesPolicyViolation,
    SuccessorRequired,
    VersionRegression,
)
from .ports import KnowledgeAssetRepository

__all__ = [
    "AssetRelationship",
    "ContentReference",
    "DuplicateOwner",
    "DuplicateRelationship",
    "ImmutableAcceptedAsset",
    "InvalidContentReference",
    "InvalidKnowledgeAssetId",
    "InvalidKnowledgeAssetKind",
    "InvalidLifecycleTransition",
    "InvalidOwner",
    "InvalidRelationship",
    "InvalidSemanticVersion",
    "InvalidSuccessor",
    "KindIdentifierMismatch",
    "KnowledgeAsset",
    "KnowledgeAssetAlreadyExists",
    "KnowledgeAssetError",
    "KnowledgeAssetId",
    "KnowledgeAssetKind",
    "KnowledgeAssetNotFound",
    "KnowledgeAssetRepository",
    "KnowledgeAssetStatus",
    "LastOwnerRemoval",
    "Owner",
    "RelationshipNotFound",
    "RelationshipTargetNotFound",
    "RelationshipType",
    "SemanticVersion",
    "SeriesPolicy",
    "SeriesPolicyViolation",
    "SuccessorRequired",
    "SuccessorSummary",
    "VersionRegression",
]
